# Heart Disease Analysis

## Data Preperation and Review

In [51]:
import statistics
import pandas as pd
import numpy as nu
import matplotlib.pyplot as plt

In [52]:
Hrt =pd.read_csv(r"C:\Users\USER\Downloads\Dataset Heart Disease.csv")

In [53]:
print(Hrt.shape)

(1048, 13)

In [54]:
Data_Head = Hrt.head()
print(Data_Head)

   Unnamed: 0  age  sex  chest pain type  resting bps  cholesterol  \
0           0   40    1                2          140        289.0
1           1   49    0                3          160        180.0
2           2   37    1                2          130        283.0
3           3   48    0                4          138        214.0
4           4   54    1                3          150        195.0

   fasting blood sugar  resting ecg  max heart rate  exercise angina  oldpeak  \
0                    0            0             172                0      0.0
1                    0            0             156                0      1.0
2                    0            1              98                0      0.0
3                    0            0             108                1      1.5
4                    0            0             122                0      0.0

   ST slope  target
0         1       0
1         2       1
2         1       0
3         2       1
4         1       0

In [55]:
info = Hrt.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1048 non-null   int64
 1   age                  1048 non-null   int64
 2   sex                  1048 non-null   int64
 3   chest pain type      1048 non-null   int64
 4   resting bps          1048 non-null   int64
 5   cholesterol          1048 non-null   float64
 6   fasting blood sugar  1048 non-null   int64
 7   resting ecg          1048 non-null   int64
 8   max heart rate       1048 non-null   int64
 9   exercise angina      1048 non-null   int64
 10  oldpeak              1048 non-null   float64
 11  ST slope             1048 non-null   int64
 12  target               1048 non-null   int64
dtypes: float64(2), int64(11)
memory usage: 106.6 KB
None

In [56]:
view_data_details = Hrt.describe()
print(view_data_details)

        Unnamed: 0          age          sex  chest pain type  resting bps  \
count  1048.000000  1048.000000  1048.000000      1048.000000  1048.000000
mean    390.841603    53.325382     0.734733         2.817748   132.613550
std     307.916633     9.397822     0.441686         1.118649    17.367605
min       0.000000    28.000000     0.000000         1.000000    92.000000
25%     130.750000    46.000000     0.000000         2.000000   120.000000
50%     262.000000    54.000000     1.000000         3.000000   130.000000
75%     657.250000    60.000000     1.000000         4.000000   140.000000
max    1189.000000    77.000000     1.000000         4.000000   200.000000

       cholesterol  fasting blood sugar  resting ecg  max heart rate  \
count  1048.000000          1048.000000  1048.000000     1048.000000
mean    245.172710             0.162214     0.606870      142.918893
std      57.101359             0.368823     0.763313       24.427115
min      85.000000             0.000000     0.000000       69.000000
25%     208.000000             0.000000     0.000000      125.000000
50%     239.000000             0.000000     0.000000      144.000000
75%     275.000000             0.000000     1.000000      162.000000
max     603.000000             1.000000     2.000000      202.000000

       exercise angina      oldpeak     ST slope       target
count      1048.000000  1048.000000  1048.000000  1048.000000
mean          0.368321     0.942366     1.532443     0.496183
std           0.482579     1.100429     0.611023     0.500224
min           0.000000    -0.100000     0.000000     0.000000
25%           0.000000     0.000000     1.000000     0.000000
50%           0.000000     0.600000     2.000000     0.000000
75%           1.000000     1.600000     2.000000     1.000000
max           1.000000     6.200000     3.000000     1.000000

Target= Heart Disease(1)
Sex= Male(1), Female(0)

Remove unnecessary data

In [57]:
Hrt = Hrt.drop(columns=['Unnamed: 0'])

In [58]:
DICT = {1:'Male',0:'Female'}
Hrt['sex'] =Hrt['sex'].replace(DICT).astype('category')
Hrt.head()

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0
1,49,Female,3,160,180.0,0,0,156,0,1.0,2,1
2,37,Male,2,130,283.0,0,1,98,0,0.0,1,0
3,48,Female,4,138,214.0,0,0,108,1,1.5,2,1
4,54,Male,3,150,195.0,0,0,122,0,0.0,1,0

In [59]:
Hrt['target'].value_counts()

target
0    528
1    520
Name: count, dtype: int64

In [60]:
Hrt.head(1)

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0

In [61]:
pd.crosstab(Hrt.sex, Hrt.cholesterol)

cholesterol,85.0,100.0,110.0,113.0,117.0,123.0,126.0,129.0,131.0,132.0,...,412.0,417.0,458.0,466.0,468.0,491.0,518.0,529.0,564.0,603.0
sex,,,,,,,,,,,,,,,,,,,,,
Female,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,2,0
Male,1,2,1,1,1,1,3,1,2,1,...,1,0,1,1,0,1,1,1,0,1

## Data Relations

### Age

#### Age 61 - Up

In [62]:
Age_61_Up =Hrt[(Hrt['age'] >= 61) ]
Age_61_Up

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
36,65,Male,4,140,306.0,1,0,87,1,1.5,2,1
82,63,Male,4,150,223.0,0,0,115,0,0.0,2,1
85,66,Male,4,140,139.0,0,0,94,1,1.0,2,1
86,65,Male,4,170,263.0,1,0,112,1,2.0,2,1
100,65,Male,4,130,275.0,0,1,115,1,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1035,61,Male,1,138,166.0,0,0,125,1,3.6,1,0
1036,65,Male,1,120,177.0,0,1,140,0,0.4,2,1
1037,66,Female,4,150,226.0,0,1,114,0,2.6,0,1
1042,64,Male,3,140,335.0,0,1,158,0,0.0,2,0
1043,68,Female,3,120,211.0,0,0,115,0,1.5,1,1

In [63]:
age_61_up_chol_avg = Age_61_Up['cholesterol'].mean()
age_61_cpt_avg = Age_61_Up['chest pain type'].mean()
age_61_mhr_avg = Age_61_Up['max heart rate'].mean()
age_61_bps_avg = Age_61_Up['resting bps'].mean()
age_61_agnia_count = (114/239)*100
Age_61_Up['target'].value_counts()
age_61_target_count = (143/239)*100

#### Age 51 - 60

In [64]:
Age_51_60 = Hrt[ (Hrt['age'] >= 51) & (Hrt['age'] <= 60) ]
Age_51_60

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
4,54,Male,3,150,195.0,0,0,122,0,0.0,1,0
7,54,Male,2,110,208.0,0,0,142,0,0.0,1,0
11,58,Male,2,136,164.0,0,1,99,1,2.0,2,1
15,54,Female,2,120,273.0,0,0,150,0,1.5,2,0
18,60,Male,4,100,248.0,0,0,125,0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1040,60,Female,3,120,178.0,1,1,96,0,0.0,2,1
1041,52,Male,1,108,233.0,1,1,147,0,0.1,2,1
1045,52,Male,1,128,255.0,0,1,161,1,0.0,2,0
1046,59,Male,4,160,273.0,0,0,125,0,0.0,2,0
1047,54,Male,1,120,188.0,0,1,113,0,1.4,1,0

In [65]:
age_51_chol_avg = Age_51_60['cholesterol'].mean()
age_51_cpt_avg = Age_51_60['chest pain type'].mean()
age_51_mhr_avg = Age_51_60['max heart rate'].mean()
age_51_bps_avg = Age_51_60['resting bps'].mean()
Age_51_60['exercise angina'].value_counts()
age_51_agnia_count = (180/433)*100
Age_51_60['target'].value_counts()
age_51_target_count = (218/433)*100

#### Age 41 - 50

In [66]:
Age_41_50 = Hrt[(Hrt['age'] >= 41) & (Hrt['age'] <= 50) ]
Age_41_50

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,49,Female,3,160,180.0,0,0,156,0,1.0,2,1
3,48,Female,4,138,214.0,0,0,108,1,1.5,2,1
6,45,Female,2,130,237.0,0,0,170,0,0.0,1,0
9,48,Female,2,120,284.0,0,0,120,0,0.0,1,0
13,49,Male,4,140,234.0,0,0,140,1,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1021,44,Male,3,140,235.0,0,0,180,0,0.0,2,1
1024,50,Female,1,110,254.0,0,0,159,0,0.0,2,1
1026,46,Male,2,101,197.0,1,1,156,0,0.0,2,1
1032,43,Male,1,115,303.0,0,1,181,0,1.2,1,1
1044,44,Female,3,108,141.0,0,1,175,0,0.6,1,1

In [67]:
age_41_chol_avg = Age_41_50['cholesterol'].mean()
age_41_cpt_avg = Age_41_50['chest pain type'].mean()
age_41_mhr_avg = Age_41_50['max heart rate'].mean()
age_41_bps_avg = Age_41_50['resting bps'].mean()
Age_41_50['exercise angina'].value_counts()
age_41_agnia_count = (73/277)*100
Age_41_50['target'].value_counts()
age_41_target_count = (126/277)*100

#### Age 31 - 40

In [68]:
Age_31_40 = Hrt[(Hrt['age'] >= 31) & (Hrt['age'] <=40) ]
Age_31_40

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0
2,37,Male,2,130,283.0,0,1,98,0,0.0,1,0
5,39,Male,3,120,339.0,0,0,170,0,0.0,1,0
8,37,Male,4,140,207.0,0,0,130,1,1.5,2,1
10,37,Female,3,130,211.0,0,0,142,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
931,38,Male,4,120,231.0,0,1,182,1,3.8,1,0
943,35,Male,2,122,192.0,0,1,174,0,0.0,2,1
966,37,Male,3,130,250.0,0,1,187,0,3.5,0,1
991,35,Male,1,126,282.0,0,0,156,1,0.0,2,0
1039,39,Male,1,118,219.0,0,1,140,0,1.2,1,0

In [69]:
age_31_chol_avg = Age_31_40['cholesterol'].mean()
age_31_cpt_avg = Age_31_40['chest pain type'].mean()
age_31_mhr_avg = Age_31_40['max heart rate'].mean()
age_31_bps_avg = Age_31_40['resting bps'].mean()
Age_31_40['exercise angina'].value_counts()
age_31_agnia_count = (19/93)*100
Age_31_40['target'].value_counts()
age_31_target_count = (32/93)*100

#### Age 20 - 30

In [70]:
Age_20_30 = Hrt[(Hrt['age'] < 31) ]
Age_20_30

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
170,29,Male,2,120,243.0,0,0,160,0,0.0,1,0
208,28,Male,2,130,132.0,0,2,185,0,0.0,1,0
215,30,Female,1,170,237.0,0,1,170,0,0.0,1,0
219,29,Male,2,140,263.0,0,0,170,0,0.0,1,0
657,29,Male,2,130,204.0,0,2,202,0,0.0,1,0
802,29,Male,2,130,204.0,0,0,202,0,0.0,2,1

In [71]:
Age_20_30['target'].value_counts()

target
0    5
1    1
Name: count, dtype: int64

In [72]:
age_20_chol_avg = Age_20_30['cholesterol'].mean()
age_20_cpt_avg = Age_20_30['chest pain type'].mean()
age_20_mhr_avg = Age_20_30['max heart rate'].mean()
age_20_bps_avg = Age_20_30['resting bps'].mean()
Age_20_30['exercise angina'].value_counts()
age_20_agnia_count = (0/6)*100
Age_20_30['target'].value_counts()
age_20_target_count = (1/6)*100

### Gender

In [73]:
Male = Hrt[(Hrt['sex'] == 'Male' )]
Male

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0
2,37,Male,2,130,283.0,0,1,98,0,0.0,1,0
4,54,Male,3,150,195.0,0,0,122,0,0.0,1,0
5,39,Male,3,120,339.0,0,0,170,0,0.0,1,0
7,54,Male,2,110,208.0,0,0,142,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1041,52,Male,1,108,233.0,1,1,147,0,0.1,2,1
1042,64,Male,3,140,335.0,0,1,158,0,0.0,2,0
1045,52,Male,1,128,255.0,0,1,161,1,0.0,2,0
1046,59,Male,4,160,273.0,0,0,125,0,0.0,2,0
1047,54,Male,1,120,188.0,0,1,113,0,1.4,1,0

In [74]:
Male['target'].value_counts()

target
1    408
0    362
Name: count, dtype: int64

In [75]:
male_age_avg = Male['age'].mean()
male_age_sd = Male['age'].std()
male_chol_avg = Male['cholesterol'].mean()
male_cpt_avg = Male['chest pain type'].mean()
male_mhr_avg = Male['max heart rate'].mean()
male_bps_avg = Male['resting bps'].mean()
Male['exercise angina'].value_counts()
male_agnia_count = (324/770)*100
Male['target'].value_counts()
male_target_count =(408/770)*100

In [76]:
Female = Hrt[(Hrt['sex'] == 'Female' )]
Female

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,49,Female,3,160,180.0,0,0,156,0,1.0,2,1
3,48,Female,4,138,214.0,0,0,108,1,1.5,2,1
6,45,Female,2,130,237.0,0,0,170,0,0.0,1,0
9,48,Female,2,120,284.0,0,0,120,0,0.0,1,0
10,37,Female,3,130,211.0,0,0,142,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1037,66,Female,4,150,226.0,0,1,114,0,2.6,0,1
1038,55,Female,2,135,250.0,0,0,161,0,1.4,1,1
1040,60,Female,3,120,178.0,1,1,96,0,0.0,2,1
1043,68,Female,3,120,211.0,0,0,115,0,1.5,1,1
1044,44,Female,3,108,141.0,0,1,175,0,0.6,1,1

In [77]:
Female['target'].value_counts()

target
0    166
1    112
Name: count, dtype: int64

In [78]:
female_age_avg = Female['age'].mean()
female_age_sd = Female['age'].std()
female_chol_avg = Female['cholesterol'].mean()
female_cpt_avg = Female['chest pain type'].mean()
female_mhr_avg = Female['max heart rate'].mean()
female_bps_avg = Female['resting bps'].mean()
Female['exercise angina'].value_counts()
female_agnia_count = (62 / 278) *100
Female['target'].value_counts()
female_target_count =(112 / 278) *100

## Data Analysis

Data should be sumarized on different realtional parameter such as;

Tabel 1
Rows; Male Female 
Columns ; Age(Average, Standard Diveation), Cholesterol(Average), Chest Pain Type(Avg), Target(Value Count), excercise agnia(Value Count), max heart rate(Avg), resting bps(Avg)

Tabel 2
Rows; Age Ranges
Columns ; Sex (Value Count), Cholesterol(Average), Chest Pain Type(Avg), Target(Value Count), excercise agnia(Value Count), max heart rate(Avg), resting bps(Avg)

### Gender Statistics

In [79]:
G_Sex = ['Male', 'Female']
G_Average_Age = [male_age_avg, female_age_avg]
G_Age_Variation =[male_age_sd, female_age_sd]
G_Average_Cholesterol =[male_chol_avg, female_chol_avg]
G_Average_Chest_Pain =[male_cpt_avg, female_cpt_avg]
G_Average_Max_Heart_Rate = [male_mhr_avg, female_mhr_avg]
G_Average_Resting_BPS =[male_bps_avg, female_bps_avg]
G_Excercise_Agnia =[male_agnia_count, female_agnia_count]
G_Heart_Disease = [male_target_count, female_target_count]
Gender_Stats =G_Sex, G_Average_Age, G_Age_Variation, G_Average_Cholesterol, G_Average_Chest_Pain, G_Average_Max_Heart_Rate, G_Average_Resting_BPS, G_Excercise_Agnia, G_Heart_Disease

In [80]:
GS = pd.DataFrame(Gender_Stats)
print(GS)

            0           1
0        Male      Female
1   53.298701   53.399281
2    9.369409    9.492669
3  240.655844  257.683453
4    2.890909    2.615108
5  140.931169   148.42446
6  132.705195  132.359712
7   42.077922   22.302158
8   52.987013    40.28777

In [81]:
GS_Index= pd.Index(['Gender','Average Age','Age Variation','Average Cholesterol','Average Chest Pain','Average Max Heart Rate','Average BPS','Excercise Agnia Percent','Heart Disease Percent'])
GS.index = GS_Index

In [82]:
GS_details = GS.describe()
print(GS_details)

           0       1
count      9       9
unique     9       9
top     Male  Female
freq       1       1

In [83]:
GS.head(9)

                                  0           1
Gender                         Male      Female
Average Age               53.298701   53.399281
Age Variation              9.369409    9.492669
Average Cholesterol      240.655844  257.683453
Average Chest Pain         2.890909    2.615108
Average Max Heart Rate   140.931169   148.42446
Average BPS              132.705195  132.359712
Excercise Agnia Percent   42.077922   22.302158
Heart Disease Percent     52.987013    40.28777

### Age Group Statistics

In [84]:
AG_Age_Group = ['20-30'], ['31-40'], ['41-50'], ['51-60'], ['61-Up']
AG_Average_Cholesterol =[age_20_chol_avg, age_31_chol_avg, age_41_chol_avg, age_51_chol_avg, age_61_up_chol_avg]
AG_Average_Chest_Pain =[age_20_cpt_avg,age_31_cpt_avg,age_41_cpt_avg,age_51_cpt_avg,age_61_cpt_avg]
AG_Average_Max_Heart_Rate = [age_20_mhr_avg,age_31_mhr_avg,age_41_mhr_avg,age_51_mhr_avg,age_61_mhr_avg]
AG_Average_Resting_BPS =[age_20_bps_avg,age_31_bps_avg,age_41_bps_avg,age_51_bps_avg,age_61_bps_avg]
AG_Excercise_Agnia =[age_20_agnia_count,age_31_agnia_count,age_41_agnia_count,age_51_agnia_count,age_61_agnia_count]
AG_Heart_Disease = [age_20_target_count,age_31_target_count,age_41_target_count,age_51_target_count,age_61_target_count]

AG_Stats = AG_Age_Group,AG_Average_Cholesterol,AG_Average_Chest_Pain,AG_Average_Max_Heart_Rate,AG_Average_Resting_BPS,AG_Excercise_Agnia,AG_Heart_Disease

In [85]:
AG = pd.DataFrame(AG_Stats)
print(AG)

            0           1           2           3           4
0     [20-30]     [31-40]     [41-50]     [51-60]     [61-Up]
1  213.833333  234.913978  238.797834   247.43418  253.242678
2    1.833333    2.763441    2.808664    2.822171    2.866109
3       181.5  158.569892  149.790614  140.581986  132.129707
4  136.666667  125.333333  127.469314  134.411085  138.050209
5         0.0   20.430108   26.353791   41.570439   47.698745
6   16.666667   34.408602   45.487365    50.34642   59.832636

In [86]:
AG_Index= pd.Index(['Age Groups','Average Cholesterol','Average Chest Pain','Average Max Heart Rate','Average BPS','Excercise Agnia Percent','Heart Disease Percent'])
AG.index = AG_Index

In [87]:
AG.head(7)

,0,1,2,3,4
Age Groups,[20-30],[31-40],[41-50],[51-60],[61-Up]
Average Cholesterol,213.833333,234.913978,238.797834,247.43418,253.242678
Average Chest Pain,1.833333,2.763441,2.808664,2.822171,2.866109
Average Max Heart Rate,181.5,158.569892,149.790614,140.581986,132.129707
Average BPS,136.666667,125.333333,127.469314,134.411085,138.050209
Excercise Agnia Percent,0.0,20.430108,26.353791,41.570439,47.698745
Heart Disease Percent,16.666667,34.408602,45.487365,50.34642,59.832636

In [87]:
AG.head(7)

,0,1,2,3,4
Age Groups,[20-30],[31-40],[41-50],[51-60],[61-Up]
Average Cholesterol,213.833333,234.913978,238.797834,247.43418,253.242678
Average Chest Pain,1.833333,2.763441,2.808664,2.822171,2.866109
Average Max Heart Rate,181.5,158.569892,149.790614,140.581986,132.129707
Average BPS,136.666667,125.333333,127.469314,134.411085,138.050209
Excercise Agnia Percent,0.0,20.430108,26.353791,41.570439,47.698745
Heart Disease Percent,16.666667,34.408602,45.487365,50.34642,59.832636

## Data Visualization

For a visual representation on the results of this analysis can be viewd in this link: 
https://app.powerbi.com/groups/me/reports/64485544-d25b-4b69-9e82-40e711e65552?ctid=f18ec70a-ed62-4182-b0d2-f888042cd62c&pbi_source=linkShare