# Heart Disease Analysis

## Data Preperation and Review

In [1]:
import pandas as pd
import numpy as nu
import matplotlib.pyplot as plt

In [2]:
Hrt =pd.read_csv(r"C:\Users\USER\Downloads\Dataset Heart Disease.csv")

In [3]:
print(Hrt.shape)

(1048, 13)

In [4]:
Data_Head = Hrt.head()
print(Data_Head)

   Unnamed: 0  age  sex  chest pain type  resting bps  cholesterol  \
0           0   40    1                2          140        289.0
1           1   49    0                3          160        180.0
2           2   37    1                2          130        283.0
3           3   48    0                4          138        214.0
4           4   54    1                3          150        195.0

   fasting blood sugar  resting ecg  max heart rate  exercise angina  oldpeak  \
0                    0            0             172                0      0.0
1                    0            0             156                0      1.0
2                    0            1              98                0      0.0
3                    0            0             108                1      1.5
4                    0            0             122                0      0.0

   ST slope  target
0         1       0
1         2       1
2         1       0
3         2       1
4         1       0

In [5]:
info = Hrt.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1048 non-null   int64
 1   age                  1048 non-null   int64
 2   sex                  1048 non-null   int64
 3   chest pain type      1048 non-null   int64
 4   resting bps          1048 non-null   int64
 5   cholesterol          1048 non-null   float64
 6   fasting blood sugar  1048 non-null   int64
 7   resting ecg          1048 non-null   int64
 8   max heart rate       1048 non-null   int64
 9   exercise angina      1048 non-null   int64
 10  oldpeak              1048 non-null   float64
 11  ST slope             1048 non-null   int64
 12  target               1048 non-null   int64
dtypes: float64(2), int64(11)
memory usage: 106.6 KB
None

In [6]:
view_data_details = Hrt.describe()
print(view_data_details)

        Unnamed: 0          age          sex  chest pain type  resting bps  \
count  1048.000000  1048.000000  1048.000000      1048.000000  1048.000000
mean    390.841603    53.325382     0.734733         2.817748   132.613550
std     307.916633     9.397822     0.441686         1.118649    17.367605
min       0.000000    28.000000     0.000000         1.000000    92.000000
25%     130.750000    46.000000     0.000000         2.000000   120.000000
50%     262.000000    54.000000     1.000000         3.000000   130.000000
75%     657.250000    60.000000     1.000000         4.000000   140.000000
max    1189.000000    77.000000     1.000000         4.000000   200.000000

       cholesterol  fasting blood sugar  resting ecg  max heart rate  \
count  1048.000000          1048.000000  1048.000000     1048.000000
mean    245.172710             0.162214     0.606870      142.918893
std      57.101359             0.368823     0.763313       24.427115
min      85.000000             0.000000     0.000000       69.000000
25%     208.000000             0.000000     0.000000      125.000000
50%     239.000000             0.000000     0.000000      144.000000
75%     275.000000             0.000000     1.000000      162.000000
max     603.000000             1.000000     2.000000      202.000000

       exercise angina      oldpeak     ST slope       target
count      1048.000000  1048.000000  1048.000000  1048.000000
mean          0.368321     0.942366     1.532443     0.496183
std           0.482579     1.100429     0.611023     0.500224
min           0.000000    -0.100000     0.000000     0.000000
25%           0.000000     0.000000     1.000000     0.000000
50%           0.000000     0.600000     2.000000     0.000000
75%           1.000000     1.600000     2.000000     1.000000
max           1.000000     6.200000     3.000000     1.000000

Target= Heart Disease(1)
Sex= Male(1), Female(0)

Remove unnecessary data

In [7]:
Hrt = Hrt.drop(columns=['Unnamed: 0'])

In [8]:
DICT = {1:'Male',0:'Female'}
Hrt['sex'] =Hrt['sex'].replace(DICT).astype('category')
Hrt.head()

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0
1,49,Female,3,160,180.0,0,0,156,0,1.0,2,1
2,37,Male,2,130,283.0,0,1,98,0,0.0,1,0
3,48,Female,4,138,214.0,0,0,108,1,1.5,2,1
4,54,Male,3,150,195.0,0,0,122,0,0.0,1,0

In [17]:
Hrt['target'].value_counts()

target
0    528
1    520
Name: count, dtype: int64

In [ ]:
plotCorrelationMatrix(Hrt, 8)

In [16]:
nu.corrcoef(Hrt)

TypeError: unsupported operand type(s) for +: 'int' and 'str'

In [14]:
correlation = Hrt[''].corr(Hrt['y'])

ValueError: could not convert string to float: 'Male'

In [ ]:
plt.cohere(Hrt)

In [18]:
Hrt.head(1)

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0

In [30]:
pd.crosstab(Hrt.sex, Hrt.cholesterol)

cholesterol,85.0,100.0,110.0,113.0,117.0,123.0,126.0,129.0,131.0,132.0,...,412.0,417.0,458.0,466.0,468.0,491.0,518.0,529.0,564.0,603.0
sex,,,,,,,,,,,,,,,,,,,,,
Female,0,0,0,0,0,0,0,0,0,0,...,0,2,0,0,1,0,0,0,2,0
Male,1,2,1,1,1,1,3,1,2,1,...,1,0,1,1,0,1,1,1,0,1

## Data Relations

### Age

#### Age 61 - Up

In [61]:
Age_61_Up =Hrt[(Hrt['age'] >= 61) ]
Age_61_Up

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
36,65,Male,4,140,306.0,1,0,87,1,1.5,2,1
82,63,Male,4,150,223.0,0,0,115,0,0.0,2,1
85,66,Male,4,140,139.0,0,0,94,1,1.0,2,1
86,65,Male,4,170,263.0,1,0,112,1,2.0,2,1
100,65,Male,4,130,275.0,0,1,115,1,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...
1035,61,Male,1,138,166.0,0,0,125,1,3.6,1,0
1036,65,Male,1,120,177.0,0,1,140,0,0.4,2,1
1037,66,Female,4,150,226.0,0,1,114,0,2.6,0,1
1042,64,Male,3,140,335.0,0,1,158,0,0.0,2,0
1043,68,Female,3,120,211.0,0,0,115,0,1.5,1,1

#### Age 51 - 60

In [60]:
Age_51_60 = Hrt[(Hrt['age'] >= 41) (Hrt['age'] <= 50) ]
Age_51_60

age
54    63
58    55
57    48
52    43
55    43
59    40
56    39
51    38
62    36
60    33
53    31
63    28
64    27
61    27
65    24
67    22
66    17
69    12
68    11
70     9
71     8
74     6
72     3
77     3
75     3
76     3
Name: count, dtype: int64

#### Age 41 - 50

In [ ]:
Age_41_50 = Hrt[(Hrt['age'] >= 41) (Hrt['age'] <= 50) ]
Age_40_50

#### Age 31 - 40

In [47]:
Age_31_40 = Hrt[(Hrt['age'] >= 31) (Hrt['age'] <=40) ]
Age_30_40

InvalidIndexError: (0       True
1       True
2       True
3       True
4       True
        ...
1043    True
1044    True
1045    True
1046    True
1047    True
Name: age, Length: 1048, dtype: bool, 0       True
1       True
2       True
3       True
4       True
        ...
1043    True
1044    True
1045    True
1046    True
1047    True
Name: age, Length: 1048, dtype: bool)

#### Age 20 - 30

In [51]:
Age_20_30 = Hrt[(Hrt['age'] < 31) ]
Age_20_30

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
170,29,Male,2,120,243.0,0,0,160,0,0.0,1,0
208,28,Male,2,130,132.0,0,2,185,0,0.0,1,0
215,30,Female,1,170,237.0,0,1,170,0,0.0,1,0
219,29,Male,2,140,263.0,0,0,170,0,0.0,1,0
657,29,Male,2,130,204.0,0,2,202,0,0.0,1,0
802,29,Male,2,130,204.0,0,0,202,0,0.0,2,1

### Gender

In [ ]:
Male = Hrt[(Hrt['sex'] == 'Male' )]
Male

In [53]:
Female = Hrt[(Hrt['sex'] == 'Female' )]
Female

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,49,Female,3,160,180.0,0,0,156,0,1.0,2,1
3,48,Female,4,138,214.0,0,0,108,1,1.5,2,1
6,45,Female,2,130,237.0,0,0,170,0,0.0,1,0
9,48,Female,2,120,284.0,0,0,120,0,0.0,1,0
10,37,Female,3,130,211.0,0,0,142,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...
1037,66,Female,4,150,226.0,0,1,114,0,2.6,0,1
1038,55,Female,2,135,250.0,0,0,161,0,1.4,1,1
1040,60,Female,3,120,178.0,1,1,96,0,0.0,2,1
1043,68,Female,3,120,211.0,0,0,115,0,1.5,1,1
1044,44,Female,3,108,141.0,0,1,175,0,0.6,1,1

## Data Visualization

In [ ]:
Hrt['age'].plot(kind='box' , vert=True, figsize=(14,6))

In [ ]:
plt.bar(Hrt['age'],Hrt['target'])

In [ ]:
Hrt['chest pain type'].plot(kind='box' , vert=True, figsize=(14,6))

In [ ]:
Male['age'].plot(kind='box')

In [ ]:
Female['age'].plot(kind = 'box')

In [ ]:
ECG_Male

In [ ]:
Angina_No_Col_High

In [ ]:
Angina_Yes_Col_High

In [ ]:
High_Col_Pain

In [ ]:
Low_Col_Pain

In [ ]:
Resting_High_HR

In [ ]:
High_Peak_ECG

## Data Analysis

Data should be sumarized on different realtional parameter such as;

Tabel 1
Rows; Male Female 
Columns ; Age(Average, Standard Diveation), Cholesterol(Average), Chest Pain Type(Avg), Target(Value Count), excercise agnia(Value Count), max heart rate(Avg), resting bps(Avg)

Tabel 1
Rows; Age Ranges
Columns ; Sex (,Age(Average, Standard Diveation), Cholesterol(Average), Chest Pain Type(Avg), Target(Value Count), excercise agnia(Value Count), max heart rate(Avg), resting bps(Avg)

In [25]:
Hrt.head(1)

,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,40,Male,2,140,289.0,0,0,172,0,0.0,1,0

In [ ]:
Hrt

In [31]:
pd.crosstab(Hrt.sex, Hrt.oldpeak)

oldpeak,-0.1,0.0,0.1,0.2,0.3,0.4,0.5,0.6,0.7,0.8,...,3.4,3.5,3.6,3.8,4.0,4.2,4.4,5.0,5.6,6.2
sex,,,,,,,,,,,,,,,,,,,,,
Female,0,128,2,12,4,4,3,12,2,7,...,2,0,2,0,4,0,0,0,0,2
Male,1,287,15,19,8,15,14,16,0,21,...,4,3,6,2,7,4,2,1,2,0

In [ ]:
Analysis = df.