# Heart Disease Analysis 
Import Packages and Files and proceed to extract get core information about the data set

In [1]:
import pandas as pd
import numpy as nu
import matplotlib as mt

In [2]:
Hrt =pd.read_csv(r"C:\Users\USER\Downloads\Dataset Heart Disease.csv")

In [3]:
Data_Head = Hrt.head()
print(Data_Head)

   Unnamed: 0  age  sex  chest pain type  resting bps  cholesterol  \
0           0   40    1                2          140        289.0
1           1   49    0                3          160        180.0
2           2   37    1                2          130        283.0
3           3   48    0                4          138        214.0
4           4   54    1                3          150        195.0

   fasting blood sugar  resting ecg  max heart rate  exercise angina  oldpeak  \
0                    0            0             172                0      0.0
1                    0            0             156                0      1.0
2                    0            1              98                0      0.0
3                    0            0             108                1      1.5
4                    0            0             122                0      0.0

   ST slope  target
0         1       0
1         2       1
2         1       0
3         2       1
4         1       0

In [4]:
info = Hrt.info()
print(info)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1048 entries, 0 to 1047
Data columns (total 13 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1048 non-null   int64
 1   age                  1048 non-null   int64
 2   sex                  1048 non-null   int64
 3   chest pain type      1048 non-null   int64
 4   resting bps          1048 non-null   int64
 5   cholesterol          1048 non-null   float64
 6   fasting blood sugar  1048 non-null   int64
 7   resting ecg          1048 non-null   int64
 8   max heart rate       1048 non-null   int64
 9   exercise angina      1048 non-null   int64
 10  oldpeak              1048 non-null   float64
 11  ST slope             1048 non-null   int64
 12  target               1048 non-null   int64
dtypes: float64(2), int64(11)
memory usage: 106.6 KB
None

In [5]:
print(Hrt.shape)

(1048, 13)

In [7]:
view_data_details = Hrt.describe()
print(view_data_details)

        Unnamed: 0          age          sex  chest pain type  resting bps  \
count  1048.000000  1048.000000  1048.000000      1048.000000  1048.000000
mean    390.841603    53.325382     0.734733         2.817748   132.613550
std     307.916633     9.397822     0.441686         1.118649    17.367605
min       0.000000    28.000000     0.000000         1.000000    92.000000
25%     130.750000    46.000000     0.000000         2.000000   120.000000
50%     262.000000    54.000000     1.000000         3.000000   130.000000
75%     657.250000    60.000000     1.000000         4.000000   140.000000
max    1189.000000    77.000000     1.000000         4.000000   200.000000

       cholesterol  fasting blood sugar  resting ecg  max heart rate  \
count  1048.000000          1048.000000  1048.000000     1048.000000
mean    245.172710             0.162214     0.606870      142.918893
std      57.101359             0.368823     0.763313       24.427115
min      85.000000             0.000000     0.000000       69.000000
25%     208.000000             0.000000     0.000000      125.000000
50%     239.000000             0.000000     0.000000      144.000000
75%     275.000000             0.000000     1.000000      162.000000
max     603.000000             1.000000     2.000000      202.000000

       exercise angina      oldpeak     ST slope       target
count      1048.000000  1048.000000  1048.000000  1048.000000
mean          0.368321     0.942366     1.532443     0.496183
std           0.482579     1.100429     0.611023     0.500224
min           0.000000    -0.100000     0.000000     0.000000
25%           0.000000     0.000000     1.000000     0.000000
50%           0.000000     0.600000     2.000000     0.000000
75%           1.000000     1.600000     2.000000     1.000000
max           1.000000     6.200000     3.000000     1.000000

Target= Heart Disease(1)
Sex= Male(1), Female(0)

In [8]:
Hrt['fasting blood sugar'].value_counts()

fasting blood sugar
0    878
1    170
Name: count, dtype: int64

In [9]:
Hrt['sex']

0       1
1       0
2       1
3       0
4       1
       ..
1043    0
1044    0
1045    1
1046    1
1047    1
Name: sex, Length: 1048, dtype: int64

In [10]:
Hrt['sex'].value_counts()

sex
1    770
0    278
Name: count, dtype: int64

In [15]:
High_CP = Hrt[Hrt['chest pain type'] > 3]
High_CP

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
3,3,48,0,4,138,214.0,0,0,108,1,1.5,2,1
8,8,37,1,4,140,207.0,0,0,130,1,1.5,2,1
13,13,49,1,4,140,234.0,0,0,140,1,1.0,2,1
16,16,38,1,4,110,196.0,0,0,166,0,0.0,2,1
18,18,60,1,4,100,248.0,0,0,125,0,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1017,271,59,1,4,178,270.0,0,0,145,0,4.2,0,1
1033,287,69,0,4,140,239.0,0,1,151,0,1.8,2,1
1034,288,65,1,4,138,282.0,1,0,174,0,1.4,1,0
1037,291,66,0,4,150,226.0,0,1,114,0,2.6,0,1
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0

### High Cholesterole levels 
High number of people with cholesterole level above the reaserched average of 170

In [17]:
Hrt[Hrt['cholesterol'] > 170]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,0,40,1,2,140,289.0,0,0,172,0,0.0,1,0
1,1,49,0,3,160,180.0,0,0,156,0,1.0,2,1
2,2,37,1,2,130,283.0,0,1,98,0,0.0,1,0
3,3,48,0,4,138,214.0,0,0,108,1,1.5,2,1
4,4,54,1,3,150,195.0,0,0,122,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1043,297,68,0,3,120,211.0,0,0,115,0,1.5,1,1
1045,299,52,1,1,128,255.0,0,1,161,1,0.0,2,0
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0
1047,301,54,1,1,120,188.0,0,1,113,0,1.4,1,0

Old age with high heart rate

In [18]:
Hrt[(Hrt['max heart rate'] > 142) & (Hrt['age'] > 50) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
15,15,54,0,2,120,273.0,0,0,150,0,1.5,2,0
29,29,51,1,2,125,188.0,0,0,145,0,0.0,1,0
43,43,52,1,3,140,259.0,0,1,170,0,0.0,1,0
55,55,51,0,2,160,194.0,0,0,170,0,0.0,1,0
70,70,57,1,2,140,265.0,0,1,145,1,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,288,65,1,4,138,282.0,1,0,174,0,1.4,1,0
1038,292,55,0,2,135,250.0,0,0,161,0,1.4,1,1
1041,295,52,1,1,108,233.0,1,1,147,0,0.1,2,1
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1045,299,52,1,1,128,255.0,0,1,161,1,0.0,2,0

Less than 50 with high heart rate.

In [19]:
Hrt[(Hrt['max heart rate'] > 142) & (Hrt['age'] < 50) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,0,40,1,2,140,289.0,0,0,172,0,0.0,1,0
1,1,49,0,3,160,180.0,0,0,156,0,1.0,2,1
5,5,39,1,3,120,339.0,0,0,170,0,0.0,1,0
6,6,45,0,2,130,237.0,0,0,170,0,0.0,1,0
12,12,39,1,2,120,204.0,0,0,145,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1014,268,44,1,1,112,290.0,0,0,153,0,0.0,2,0
1021,275,44,1,3,140,235.0,0,0,180,0,0.0,2,1
1026,280,46,1,2,101,197.0,1,1,156,0,0.0,2,1
1032,286,43,1,1,115,303.0,0,1,181,0,1.2,1,1
1044,298,44,0,3,108,141.0,0,1,175,0,0.6,1,1

High Chest Pain in Males(1)

In [20]:
Hrt[(Hrt['sex'] == 1 ) & (Hrt['chest pain type'] >= 3 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
4,4,54,1,3,150,195.0,0,0,122,0,0.0,1,0
5,5,39,1,3,120,339.0,0,0,170,0,0.0,1,0
8,8,37,1,4,140,207.0,0,0,130,1,1.5,2,1
13,13,49,1,4,140,234.0,0,0,140,1,1.0,2,1
16,16,38,1,4,110,196.0,0,0,166,0,0.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1021,275,44,1,3,140,235.0,0,0,180,0,0.0,2,1
1022,276,68,1,3,118,277.0,0,1,151,0,1.0,2,1
1034,288,65,1,4,138,282.0,1,0,174,0,1.4,1,0
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0

High Chest pain in Females(0) `

In [21]:
Hrt[(Hrt['sex'] == 0 ) & (Hrt['chest pain type'] >= 3 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,1,49,0,3,160,180.0,0,0,156,0,1.0,2,1
3,3,48,0,4,138,214.0,0,0,108,1,1.5,2,1
10,10,37,0,3,130,211.0,0,0,142,0,0.0,1,0
14,14,42,0,3,115,211.0,0,1,137,0,0.0,1,0
39,39,48,0,4,150,227.0,0,0,130,1,1.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1033,287,69,0,4,140,239.0,0,1,151,0,1.8,2,1
1037,291,66,0,4,150,226.0,0,1,114,0,2.6,0,1
1040,294,60,0,3,120,178.0,1,1,96,0,0.0,2,1
1043,297,68,0,3,120,211.0,0,0,115,0,1.5,1,1
1044,298,44,0,3,108,141.0,0,1,175,0,0.6,1,1

Resting ECG(1) = heart attack

Male

In [22]:
Hrt[(Hrt['resting ecg'] == 1 ) & (Hrt['sex'] == 1 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
2,2,37,1,2,130,283.0,0,1,98,0,0.0,1,0
11,11,58,1,2,136,164.0,0,1,99,1,2.0,2,1
26,26,53,1,4,124,260.0,0,1,112,1,3.0,2,0
33,33,41,1,4,130,172.0,0,1,130,0,2.0,2,1
43,43,52,1,3,140,259.0,0,1,170,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1039,293,39,1,1,118,219.0,0,1,140,0,1.2,1,0
1041,295,52,1,1,108,233.0,1,1,147,0,0.1,2,1
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1045,299,52,1,1,128,255.0,0,1,161,1,0.0,2,0
1047,301,54,1,1,120,188.0,0,1,113,0,1.4,1,0

Female

In [23]:
Hrt[(Hrt['resting ecg'] == 1 ) & (Hrt['sex'] == 0 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
14,14,42,0,3,115,211.0,0,1,137,0,0.0,1,0
37,37,41,0,2,110,250.0,0,1,142,0,0.0,1,0
38,38,48,0,2,120,177.0,1,1,148,0,0.0,1,0
41,41,54,0,3,130,294.0,0,1,100,1,0.0,2,1
73,73,44,0,4,120,218.0,0,1,115,0,0.0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1029,283,63,0,2,140,195.0,0,1,179,0,0.0,2,1
1033,287,69,0,4,140,239.0,0,1,151,0,1.8,2,1
1037,291,66,0,4,150,226.0,0,1,114,0,2.6,0,1
1040,294,60,0,3,120,178.0,1,1,96,0,0.0,2,1
1044,298,44,0,3,108,141.0,0,1,175,0,0.6,1,1

angina(1) = Chest pain caused by reduced blood flow as a result of blocages in the blood stream

Realtion Between Angina and Cholesterol

In [24]:
Hrt[(Hrt['exercise angina'] == 1 ) & (Hrt['cholesterol'] > 250 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
23,23,44,1,2,150,288.0,0,0,150,1,3.0,2,1
26,26,53,1,4,124,260.0,0,1,112,1,3.0,2,0
36,36,65,1,4,140,306.0,1,0,87,1,1.5,2,1
41,41,54,0,3,130,294.0,0,1,100,1,0.0,2,1
45,45,59,1,3,130,318.0,0,0,120,1,1.0,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
991,245,35,1,1,126,282.0,0,0,156,1,0.0,2,0
994,248,68,1,3,180,274.0,1,0,150,1,1.6,1,0
997,251,51,0,1,130,305.0,0,1,142,1,1.2,1,0
1002,256,41,0,3,112,268.0,0,0,172,1,0.0,2,1
1045,299,52,1,1,128,255.0,0,1,161,1,0.0,2,0

In [25]:
Hrt[(Hrt['exercise angina'] == 0 ) & (Hrt['cholesterol'] > 250 ) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
0,0,40,1,2,140,289.0,0,0,172,0,0.0,1,0
2,2,37,1,2,130,283.0,0,1,98,0,0.0,1,0
5,5,39,1,3,120,339.0,0,0,170,0,0.0,1,0
9,9,48,0,2,120,284.0,0,0,120,0,0.0,1,0
15,15,54,0,2,120,273.0,0,0,150,0,1.5,2,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1027,281,55,1,2,130,262.0,0,1,155,0,0.0,2,1
1032,286,43,1,1,115,303.0,0,1,181,0,1.2,1,1
1034,288,65,1,4,138,282.0,1,0,174,0,1.4,1,0
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0

In [26]:
Hrt['cholesterol'].value_counts()

cholesterol
254.0    16
204.0    15
211.0    13
223.0    13
234.0    13
         ..
316.0     1
458.0     1
384.0     1
349.0     1
142.0     1
Name: count, Length: 221, dtype: int64

Realation Between Chest Pain and Cholesterol

In [27]:
Hrt[(Hrt['cholesterol'] > 200) & (Hrt['chest pain type'] >= 3)]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
3,3,48,0,4,138,214.0,0,0,108,1,1.5,2,1
5,5,39,1,3,120,339.0,0,0,170,0,0.0,1,0
8,8,37,1,4,140,207.0,0,0,130,1,1.5,2,1
10,10,37,0,3,130,211.0,0,0,142,0,0.0,1,0
13,13,49,1,4,140,234.0,0,0,140,1,1.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1034,288,65,1,4,138,282.0,1,0,174,0,1.4,1,0
1037,291,66,0,4,150,226.0,0,1,114,0,2.6,0,1
1042,296,64,1,3,140,335.0,0,1,158,0,0.0,2,0
1043,297,68,0,3,120,211.0,0,0,115,0,1.5,1,1
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0

In [28]:
Hrt[(Hrt['cholesterol'] < 200) & (Hrt['chest pain type'] >= 3)]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,1,49,0,3,160,180.0,0,0,156,0,1.0,2,1
4,4,54,1,3,150,195.0,0,0,122,0,0.0,1,0
16,16,38,1,4,110,196.0,0,0,166,0,0.0,2,1
31,31,56,1,3,130,167.0,0,0,114,0,0.0,1,0
33,33,41,1,4,130,172.0,0,1,130,0,2.0,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
984,238,51,1,3,110,175.0,0,1,123,0,0.6,2,1
986,240,46,0,3,142,177.0,0,0,160,1,1.4,0,1
999,253,57,1,3,150,168.0,0,1,174,0,1.6,2,1
1040,294,60,0,3,120,178.0,1,1,96,0,0.0,2,1
1044,298,44,0,3,108,141.0,0,1,175,0,0.6,1,1

In [29]:
Hrt[(Hrt['resting bps']) > (Hrt['max heart rate']) ]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
1,1,49,0,3,160,180.0,0,0,156,0,1.0,2,1
2,2,37,1,2,130,283.0,0,1,98,0,0.0,1,0
3,3,48,0,4,138,214.0,0,0,108,1,1.5,2,1
4,4,54,1,3,150,195.0,0,0,122,0,0.0,1,0
8,8,37,1,4,140,207.0,0,0,130,1,1.5,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1037,291,66,0,4,150,226.0,0,1,114,0,2.6,0,1
1040,294,60,0,3,120,178.0,1,1,96,0,0.0,2,1
1043,297,68,0,3,120,211.0,0,0,115,0,1.5,1,1
1046,300,59,1,4,160,273.0,0,0,125,0,0.0,2,0
1047,301,54,1,1,120,188.0,0,1,113,0,1.4,1,0

Old Peak relations

In [31]:
Hrt[(Hrt['oldpeak'] > 2) & (Hrt['resting ecg'] > 1 )]

,Unnamed: 0,age,sex,chest pain type,resting bps,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
369,542,76,1,3,104,113.0,0,2,120,0,3.5,3,1
406,579,57,1,4,156,173.0,0,2,119,1,3.0,3,1
443,617,70,1,4,130,322.0,0,2,109,0,2.4,2,1
452,626,63,0,4,150,407.0,0,2,154,0,4.0,2,1
460,634,53,1,4,140,203.0,1,2,155,1,3.1,3,1
463,637,67,1,4,120,229.0,0,2,129,1,2.6,2,1
471,645,58,1,3,112,230.0,0,2,165,0,2.5,2,1
474,648,66,1,4,160,228.0,0,2,138,0,2.3,1,0
476,650,59,1,4,170,326.0,0,2,140,1,3.4,3,1
499,673,61,1,4,138,166.0,0,2,125,1,3.6,2,1
507,681,63,1,1,145,233.0,1,2,150,0,2.3,3,0
519,693,45,1,4,104,208.0,0,2,148,1,3.0,2,0
530,704,59,1,1,178,270.0,0,2,145,0,4.2,3,0
532,706,50,1,4,150,243.0,0,2,128,0,2.6,2,1
535,709,54,1,4,124,266.0,0,2,109,1,2.2,2,1
550,724,60,0,4,150,258.0,0,2,157,0,2.6,2,1
560,734,56,0,4,200,288.0,1,2,133,1,4.0,3,1
564,738,54,1,4,122,286.0,0,2,116,1,3.2,2,1
576,750,64,1,4,120,246.0,0,2,96,1,2.2,3,1
591,765,58,1,3,132,224.0,0,2,173,0,3.2,1,1
606,780,58,1,4,128,259.0,0,2,130,1,3.0,2,1
629,803,56,1,4,132,184.0,0,2,105,1,2.1,2,1
645,819,60,1,4,125,258.0,0,2,141,1,2.8,2,1
654,828,51,1,3,125,245.0,1,2,166,0,2.4,2,0
656,830,58,1,4,128,216.0,0,2,131,1,2.2,2,1
664,838,65,1,4,135,254.0,0,2,127,0,2.8,2,1
670,844,43,0,4,132,341.0,1,2,136,1,3.0,2,1
678,852,62,0,4,160,164.0,0,2,145,0,6.2,3,1
680,854,43,1,4,120,177.0,0,2,120,1,2.5,2,1
686,860,62,0,4,140,268.0,0,2,160,0,3.6,3,1
691,865,60,1,3,140,185.0,0,2,155,0,3.0,2,1
692,866,60,1,4,145,282.0,0,2,142,1,2.8,2,1
704,878,60,1,4,130,206.0,0,2,132,1,2.4,2,1
729,1173,58,0,4,170,225.0,1,2,146,1,2.8,2,1
736,1180,63,1,4,140,187.0,0,2,144,1,4.0,1,1
752,6,58,1,1,114,318.0,0,2,140,0,4.4,0,0
774,28,55,0,1,180,327.0,0,2,117,1,3.4,1,0

## Data Visualization

In [1]:
Density_Plot =Hrt['age'].plot(kind='box' , vert=True, figsize=(14,6))

NameError: name 'Hrt' is not defined

In [ ]:
Hrt['chest pain type'].plot(kind='box' , vert=True, figsize=(14,6))

In [ ]:
Hrt['age'].plot(kind='bar')