# Housing Analysis

In [1]:
## Packages
import os
import pandas as pd 
import numpy as nu 
import matplotlib.pyplot as plt

## Data collection

In [2]:
path = os.getcwd()
print(path)

c:\Users\USER\Desktop\Codes\Data\Q_housing

In [3]:
data = pd.read_csv(f"{path}/quebec_housing_sales_v2.csv")

In [4]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5000 entries, 0 to 4999
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   property_id       5000 non-null   int64
 1   city              5000 non-null   object
 2   neighborhood      5000 non-null   object
 3   property_type     5000 non-null   object
 4   bedrooms          5000 non-null   int64
 5   bathrooms         5000 non-null   int64
 6   living_area_sqft  5000 non-null   int64
 7   lot_size_sqft     3789 non-null   float64
 8   year_built        5000 non-null   int64
 9   renovation_year   1592 non-null   float64
 10  garage            5000 non-null   object
 11  basement          5000 non-null   object
 12  sale_year         5000 non-null   int64
 13  sale_price        5000 non-null   int64
dtypes: float64(2), int64(7), object(5)
memory usage: 547.0+ KB

In [5]:
data.describe()

,property_id,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,sale_year,sale_price
count,5000.000000,5000.000000,5000.000000,5000.000000,3789.000000,5000.000000,1592.000000,5000.000000,5.000000e+03
mean,2500.500000,3.488200,2.325800,1313.693800,6257.154658,1983.074000,2015.054020,2023.411600,4.802140e+05
std,1443.520003,1.357435,0.968009,472.106052,2811.434500,26.483028,5.764461,1.332119,1.771254e+05
min,1.000000,1.000000,1.000000,469.000000,1570.000000,1900.000000,2005.000000,2021.000000,1.140000e+05
25%,1250.750000,2.000000,2.000000,915.000000,4086.000000,1966.000000,2010.000000,2022.000000,3.527500e+05
50%,2500.500000,3.000000,2.000000,1273.000000,5767.000000,1985.000000,2015.000000,2024.000000,4.530000e+05
75%,3750.250000,4.000000,3.000000,1650.000000,8005.000000,2004.000000,2020.000000,2025.000000,5.840000e+05
max,5000.000000,8.000000,6.000000,2967.000000,14834.000000,2023.000000,2025.000000,2025.000000,1.425000e+06

In [6]:
data.head()

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
1,2,Trois-Rivières,Cap-de-la-Madeleine,Duplex,4,4,1807,5869.0,2006,2024.0,No,Yes,2025,444000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
3,4,Laval,Fabreville,Single Family,3,3,1083,11417.0,1972,2016.0,Yes,Yes,2023,465000
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000

## Data Cleaning

In [10]:
data['property_type'].unique()

array(['Townhouse', 'Duplex', 'Single Family', 'Condo', 'Bungalow',
       'Triplex'], dtype=object)

In [12]:
data[data['lot_size_sqft'].isna()].head()

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
4,5,Longueuil,Greenfield Park,Condo,2,2,714,NaN,1997,2010.0,Yes,No,2022,371000
10,11,Longueuil,Le Vieux-Longueuil,Condo,1,2,768,NaN,2014,NaN,Yes,No,2025,523000
13,14,Repentigny,Le Gardeur,Condo,1,1,991,NaN,2002,NaN,No,No,2024,534000
15,16,Candiac,Candiac Centre,Condo,2,2,806,NaN,2010,NaN,No,No,2025,464000
16,17,Baie-Comeau,Baie-Comeau Centre,Condo,3,1,512,NaN,1984,NaN,Yes,No,2025,153000

In [13]:
data[data['renovation_year'].isna()].head()

,property_id,city,neighborhood,property_type,bedrooms,bathrooms,living_area_sqft,lot_size_sqft,year_built,renovation_year,garage,basement,sale_year,sale_price
0,1,Châteauguay,Centre-Ville,Townhouse,3,2,1160,2304.0,2022,NaN,Yes,No,2024,326000
2,3,Lévis,Charny,Townhouse,3,1,803,3387.0,1989,NaN,Yes,Yes,2025,273000
5,6,Victoriaville,Centre-Ville,Single Family,4,3,2081,5682.0,1967,NaN,Yes,Yes,2023,458000
6,7,Montréal,Outremont,Townhouse,3,3,1036,3343.0,1939,NaN,No,Yes,2023,383000
7,8,Sherbrooke,Lennoxville,Single Family,4,2,1767,4750.0,2007,NaN,Yes,Yes,2023,475000

In [14]:
data['city'].value_counts()

city
Montréal                      919
Québec                        529
Laval                         460
Longueuil                     394
Brossard                      244
Sherbrooke                    220
Gatineau                      207
Terrebonne                    174
Repentigny                    147
Trois-Rivières                137
Lévis                         124
Saint-Jean-sur-Richelieu      121
Saint-Jérôme                  117
Blainville                    112
Saguenay                       93
Mirabel                        90
Granby                         90
Drummondville                  89
Dollard-des-Ormeaux            82
Châteauguay                    81
Vaudreuil-Dorion               79
Boucherville                   72
Saint-Bruno-de-Montarville     57
Victoriaville                  56
Candiac                        55
Pointe-Claire                  51
Rimouski                       49
Alma                           36
Sept-Îles                      36
Val-d'Or                       30
Rouyn-Noranda                  27
Baie-Comeau                    22
Name: count, dtype: int64

## Data Analysis

## Data Visualization

## insights

#### Review points
> Duration between year built(renovation impact) and sale year <br>
High population density <br>
Nighborhood pefrence <br>
Family size based on bedroon/bathroom <br>
What year experienced the highest number of houses built <br>
Factors influencing sale price <br>
issues to address <br>